from .nota_fiscal import router as nota_fiscal
from .nota_servico import router as nota_servico
from .cliente import router as cliente
from .item_nota import router as item_nota
from .endereco_entrega import router as endereco_entrega
from .forma_envio import router as forma_envio
from .marcador import router as marcador
from .configuracoes import router as configuracoes
from .estoque import router as estoque