from sqlalchemy import Column, Integer, String, Text, Date, Numeric
from app.models.database import Base

class NotaServico(Base):
    __tablename__ = "servicos"
    __table_args__ = {"schema": "tiny"}

    id = Column(Integer, primary_key=True, index=True)
    tipo_de_registro = Column("tipo_de_registro", Text, nullable=True)
    numero_nfse = Column("nº_da_nota_fiscal_eletrônica", Integer, nullable=True)
    status_nfse = Column("status_da_nota_fiscal", Numeric, nullable=True)
    codigo_verificacao = Column("código_de_verificação_nf", Text, nullable=True)
    data_emissao = Column("data_da_emissão_nfs_e_dsr_e", Date, nullable=True)
    tipo_rps = Column("tipo_de_rps", Numeric, nullable=True)
    serie_rps = Column("série_do_rps", Numeric, nullable=True)
    numero_rps = Column("número_do_rps", Numeric, nullable=True)
    data_emissao_rps = Column("data_emissão_do_rps", Text, nullable=True)
    cpf_cnpj_prestador = Column("cpf_cnpj_do_prestador", Text, nullable=True)
    inscricao_municipal_prestador = Column("inscrição_municipal_do_prestador", Text, nullable=True)
    inscricao_estadual_prestador = Column("inscrição_estadual_do_prestador", Text, nullable=True)
    razao_social_prestador = Column("razão_social_do_prestador", Text, nullable=True)
    nome_fantasia_prestador = Column("nome_fantasia_do_prestador", Text, nullable=True)
    endereco_prestador = Column("endereço_do_prestador", Text, nullable=True)
    numero_endereco_prestador = Column("número_do_endereço_do_prestador", Text, nullable=True)
    complemento_endereco_prestador = Column("complemento_do_endereço_do_prestador", Text, nullable=True)
    bairro_prestador = Column("bairro_do_prestador", Text, nullable=True)
    cidade_prestador = Column("cidade_do_prestador", Text, nullable=True)
    uf_prestador = Column("uf_do_prestador", Text, nullable=True)
    cep_prestador = Column("cep_do_prestador", Text, nullable=True)
    telefone_prestador = Column("telefone_de_contato_do_prestador", Text, nullable=True)
    email_prestador = Column("email_do_prestador", Text, nullable=True)

    cpf_cnpj_tomador = Column("cpf_cnpj_do_tomador", Text, nullable=True)
    inscricao_municipal_tomador = Column("inscrição_municipal_do_tomador", Text, nullable=True)
    inscricao_estadual_tomador = Column("inscrição_estadual_do_tomador", Text, nullable=True)
    razao_social_tomador = Column("razão_social_do_tomador", Text, nullable=True)
    endereco_tomador = Column("endereço_do_tomador", Text, nullable=True)
    numero_endereco_tomador = Column("número_do_endereço_do_tomador", Text, nullable=True)
    complemento_endereco_tomador = Column("complemento_do_endereço_do_tomador", Text, nullable=True)
    bairro_tomador = Column("bairro_do_tomador", Text, nullable=True)
    cidade_tomador = Column("cidade_do_tomador", Text, nullable=True)
    uf_tomador = Column("uf_do_tomador", Text, nullable=True)
    cep_tomador = Column("cep_do_tomador", Text, nullable=True)
    telefone_tomador = Column("telefone_de_contato_do_tomador", Text, nullable=True)
    email_tomador = Column("email_do_tomador", Text, nullable=True)

    tipo_tributacao = Column("tipo_de_tributação_de_serviços", Numeric, nullable=True)
    cidade_servico = Column("cidade_de_prestação_de_serviços", Text, nullable=True)
    uf_servico = Column("uf_de_prestação_de_serviços", Text, nullable=True)
    regime_especial = Column("regime_especial_de_tributação", Numeric, nullable=True)
    simples_nacional = Column("opção_pelo_simples", Numeric, nullable=True)
    incentivo_cultural = Column("incentivo_cultural", Numeric, nullable=True)
    codigo_atividade_federal = Column("código_de_atividade_federal", Numeric, nullable=True)
    codigo_atividade_municipal = Column("código_de_atividade_municipal", Numeric, nullable=True)

    aliquota = Column("alíquota", Text, nullable=True)
    valor_servico = Column("valor_dos_serviços", Text, nullable=True)
    valor_deducoes = Column("valor_das_deduções", Text, nullable=True)
    valor_desconto_condicionado = Column("valor_do_desconto_condicionado", Text, nullable=True)
    valor_desconto_incondicionado = Column("valor_do_desconto_incondicionado", Text, nullable=True)
    valor_cofins = Column("valor_cofins", Text, nullable=True)
    valor_csll = Column("valor_csll", Text, nullable=True)
    valor_inss = Column("valor_inss", Text, nullable=True)
    valor_irpj = Column("valor_irpj", Text, nullable=True)
    valor_pis = Column("valor_pis_pasep", Text, nullable=True)
    valor_outras = Column("valor_de_outras_retenções_federais", Text, nullable=True)
    valor_iss = Column("valor_do_iss", Text, nullable=True)
    valor_credito = Column("valor_do_crédito", Text, nullable=True)

    iss_retido = Column("iss_retido", Numeric, nullable=True)
    data_cancelamento = Column("data_de_cancelamento", Text, nullable=True)
    data_competencia = Column("data_de_competência", Text, nullable=True)
    numero_guia = Column("nº_da_guia", Text, nullable=True)
    data_quitacao_guia = Column("data_da_quitação_da_guia_vinculada", Text, nullable=True)
    lote = Column("lote", Text, nullable=True)
    codigo_obra = Column("código_da_obra", Text, nullable=True)
    art = Column("art", Text, nullable=True)
    nota_fiscal_substituida = Column("nº_nota_fiscal_substituída", Text, nullable=True)
    nota_fiscal_substituta = Column("nº_nota_fiscal_substituta", Text, nullable=True)
    valor_total_recebido = Column("valor_total_recebido", Text, nullable=True)
    discriminacao_servico = Column("discriminação_dos_serviços", Text, nullable=True)
    exercicio_fg = Column("exercício_fg_nfs_e_dr", Text, nullable=True)
    mes_fg = Column("mês_fg_nfs_e_dr", Numeric, nullable=True)
